server:
  port: 8080

spring:
  application:
    name: BATCH-TEST
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false